services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./auth/miniprojet.sql:/docker-entrypoint-initdb.d/miniprojet.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - miniprojet-net

  auth-service:
    build:
      context: ./auth
    container_name: auth-service
    ports:
      - "3060:3060"
    env_file:
      - ./auth/.env
    environment:
      PORT: 3060
      GATEWAY_URL: "http://localhost:8000"
      FRONTEND_URL: "http://localhost:3000"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - miniprojet-net

  backend_nest:
    build:
      context: ./backend_nest
      dockerfile: Dockerfile
    container_name: backend_nest
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      NODE_ENV: production
      AUTH_SERVICE_URL: "http://auth-service:3060"
      GATEWAY_URL: "http://gateway:8000"
      STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET}"
    networks:
      - miniprojet-net

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
    environment:
      AUTH_SERVICE_URL: "http://auth-service:3060"
      BACKEND_SERVICE_URL: "http://backend_nest:5000"
      FRONTEND_URL: "http://localhost:3000"
      PORT: 8000
    depends_on:
      - auth-service
      - backend_nest
      - mysql-db
    networks:
      - miniprojet-net

  frontend:
    build:
      context: ./frontend
      target: runner
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
      API_URL: "http://gateway:8000"
      NEXT_PUBLIC_SUPABASE_URL: ${SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    depends_on:
      - gateway
    networks:
      - miniprojet-net

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql-db
    depends_on:
      - mysql-db
    networks:
      - miniprojet-net

volumes:
  mysql_data:

networks:
  miniprojet-net:
    driver: bridge