apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: blockchain-app
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
  - port: 3060
    targetPort: 3060
    protocol: TCP
    name: http
