apiVersion: v1
kind: Service
metadata:
  name: backend-nest-service
  namespace: blockchain-app
spec:
  type: ClusterIP
  selector:
    app: backend-nest
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
