apiVersion: v1
kind: Service
metadata:
  name: hardhat-service
  namespace: blockchain-app
spec:
  type: ClusterIP
  selector:
    app: hardhat-node
  ports:
  - port: 8545
    targetPort: 8545
    protocol: TCP
    name: rpc
